name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install Iosevka font
        run: |
          wget https://github.com/be5invis/Iosevka/releases/download/v6.0.0-preview.4/ttf-iosevka-fixed-6.0.0-preview.4.zip -O /tmp/iosevka.zip
          mkdir iosevka
          unzip /tmp/iosevka.zip -d iosevka
      - name: Compile thesis in colour
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis.tex
          pre_compile: |
            mkdir ~/.fonts
            cp iosevka/*.ttf ~/.fonts/
            fc-cache -fv
      - name: Compile thesis in black and white
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis_grayscale.tex
          pre_compile: sed '/colourflag/d' thesis.tex > thesis_grayscale.tex
      - name: Compile English abstract
        uses: xu-cheng/latex-action@v2
        with:
          root_file: abstract.tex
      - name: Remove older releases
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Latest
          files: |
            thesis.pdf
            thesis_grayscale.pdf
            abstract.pdf
          tag_name: release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
